research_task:
  description: >
    使用搜索引擎，严格收集从昨天早上9点到今天早上9点之间（最近24小时内）的AI新闻。
    
    评分标准（满分10分）：

    1. 重要性（权重35%）：
       - 全球性突破（10分）：重大技术突破、重要研究成果、行业变革性影响
       - 区域性突破（9分）：区域市场重大进展、重要技术创新
       - 重要更新（8分）：主流产品重大更新、战略合作、关键里程碑
       - 产品发布（7分）：新产品发布、重要功能更新、市场扩张
       - 一般进展（6分）：常规更新、行业动态、日常发展

    2. 相关性（权重35%）：
       - 核心技术（10分）：大模型架构、基础算法、关键突破
       - 商业落地（9分）：重要商业化进展、大规模应用
       - 技术创新（8分）：创新应用场景、技术改进
       - 基础设施（7分）：算力、框架、开发工具
       - 生态发展（6分）：行业合作、标准制定

    3. 地域平衡（权重30%）：
       国际新闻（55%）：
       - 全球领先（10分）：OpenAI、Anthropic、Google、DeepMind等全球顶级AI公司
       - 区域领先（9分）：Mistral AI、Cohere等新兴但重要的国际AI公司
       - 创新企业（8分）：有特色或创新的国际AI创业公司
       - 研究机构（7分）：国际知名高校、研究所的AI成果
       
       国内新闻（45%）：
       - 行业领军（10分）：百度、阿里、腾讯、字节等大型科技公司
       - 创新企业（9分）：智谱AI、MiniMax等新兴AI公司
       - 研究机构（8分）：国内重点高校、研究院所的AI成果
       - 产业应用（7分）：AI在各行业的落地应用
    
    搜索要求：
    1. 每个类别（大模型、AI基础设施、AI应用、AI研究）至少搜索相关新闻
    2. 对每条新闻进行评分，格式为：
       标题：xxx
       来源：xxx
       时间：xxx
       评分：
       - 重要性：X分（原因）
       - 相关性：X分（原因）
       - 地域平衡：X分（原因）
       - 最终得分：X分（重要性×0.35 + 相关性×0.35 + 地域平衡×0.30）
       内容：xxx
    3. 只收录最终得分≥7.5分的新闻
    4. 每日新闻报告中，国际新闻占比必须达到55%以上
    5. 如果发现多篇相似新闻，只保留得分最高的一篇
    6. 确保新闻来源多样化，避免过度关注单一公司
    7. 优先选择有具体技术细节或数据支持的新闻
    8. 对于重大突破性新闻，无论国内外，都应优先报道
    9. 排除包含屏蔽关键词的新闻
    
    最终输出：
    为每条新闻提供完整的评分和内容信息，按得分从高到低排序。
  expected_output: >
    一份包含至少15条相关新闻的列表，每条新闻包括标题、来源、时间、评分详情和内容摘要，其中国际新闻占比不低于55%。
  agent: researcher

analysis_task:
  description: >
    对研究员提供的新闻列表进行深入分析，选出最重要的10条新闻，生成一份结构化的中文报告。
    报告要求：
    1. 按照重要性和影响力对新闻进行排序
    2. 为每条新闻撰写简洁摘要，100-150字左右，只包含最重要的信息
    3. 使用markdown格式，保证报告结构清晰、易读
    4. 标题必须使用今天的日期，格式为"【AI日报】YYYY-MM-DD"，不要添加任何副标题
    5. 所有内容必须是最近24小时内的新闻
    6. 重要：不要在输出内容的开头添加```markdown，也不要在结尾添加```标记
    7. 每条新闻必须且只能包含两个部分：标题和摘要
    8. 标题格式为：## 序号. 标题
    9. 摘要格式为：直接写摘要内容，不要添加任何前缀或标签
    10. 绝对不要包含任何来源信息、发布时间、链接或其他元数据
    11. 不要包含核心要点、技术细节、潜在影响等任何其他部分
    12. 确保国际新闻和国内新闻的比例符合55:45的要求
  expected_output: >
    一份结构化的中文报告，包含10条重要AI新闻的简洁摘要，格式为Markdown（但不包含```标记），使用当前日期作为标题。国际新闻占比不低于55%。
  agent: analyst
  output_file: ai_news_report.md 