research_task:
  description: >
    使用搜索引擎，严格收集从昨天早上9点到今天早上9点之间（最近24小时内），包含以下关键词的新闻：
    ["openai", "anthropic", "gemini", "nvidia nim", "grok", "ollama", "watson",
    "bedrock", "azure", "cerebras", "sambanova", "deepseek", "qwen", "xAI",
    "文心一言", "豆包", "元宝",
    "人工智能", "机器学习", "深度学习", "生成式ai", "大语言模型", "神经网络",
    "计算机视觉", "自然语言处理", "强化学习", "多模态ai", "ai芯片",
    "量子计算", "自动驾驶"]
    请排除包含以下关键词的新闻：
    ["色情", "成人", "裸体", "性", "政治", "政府", "选举", "抗议", "违法", "毒品",
    "赌博", "邪教", "宗教", "恐怖主义", "暴力", "战争"]
    搜索要求：
    1. 每个关键词至少搜索一次，获取相关新闻
    2. 为每篇新闻记录标题、来源、发布时间、内容摘要和链接
    3. 按照重要性和热度排序，优先选择讨论最新技术进展、产品发布和公司重大动态的新闻
    4. 严格关注时效性，确保新闻发布时间在指定范围内（最近24小时）
    5. 明确验证每条新闻的发布日期，确保只收集最新内容
  expected_output: >
    一份包含至少15条相关新闻的列表，每条新闻包括标题、来源、发布时间、内容摘要和链接。
  agent: researcher

analysis_task:
  description: >
    对研究员提供的新闻列表进行深入分析，选出最重要的10条新闻，生成一份结构化的中文报告。
    报告要求：
    1. 按照重要性和影响力对新闻进行排序
    2. 为每条新闻撰写详细摘要，不少于150字，包含核心要点、技术细节和潜在影响
    3. 使用markdown格式，保证报告结构清晰、易读
    4. 标题必须使用今天的日期，格式为"【AI日报】YYYY-MM-DD AI热点新闻"
    5. 根据环境变量设置决定报告格式
    6. 所有内容必须是最近24小时内的新闻
    7. 重要：不要在输出内容的开头添加```markdown，也不要在结尾添加```标记
  expected_output: >
    一份结构化的中文报告，包含10条重要AI新闻的详细摘要，格式为Markdown（但不包含```标记），使用当前日期作为标题。
  agent: analyst
  output_file: ai_news_report.md 